language: generic

addons:
  apt:
    sources:
    - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
      key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    packages:
    - powershell

before_install:
  - sudo pwsh -c "Install-Module Pester -Force"
  - sudo pwsh -c "Install-Module PSScriptAnalyzer -Force"
script:
  - pwsh -f ./scripts/test.ps1
  - pwsh -c "Invoke-ScriptAnalyzer ./SpinnakerHalyard/SpinnakerHalyard.psm1 -EnableExit"
